### ISSUE TITLE
Uniform theme color.

### ISSUE THREAD

**Issue by ManasviPatidar** [mdg-iitr/Codephile_mobile#31]
Add a theme at the root level so that widgets like ProgressIndicator and DatePicker use the standard app colours.

**Comment by raghavpawar** [comment]
Hi, I would like to work on this issue.

**Comment by ManasviPatidar** [comment]
@raghavpawar The primary objective of this issue is to provide the correct colors to widgets like ProgressIndicator and DatePicker. They pick up colors from the ThemeData of the app. If this ThemeData is not provided they pick up the flutter defaults.
Your task is to add the ThemeData in the MaterialApp of our application. You only havev to add the primary color as of now.
This might help:-[https://flutter.dev/docs/cookbook/design/themes](https://flutter.dev/docs/cookbook/design/themes)
